Altex/Controllers/RoleController.cs
using System.Diagnostics;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Altex.Models;

namespace Altex.Controllers
{
    [Authorize( Roles = "Admin,SuperAdmin")]
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly ILogger<RoleController> _logger;
        public RoleController(RoleManager<IdentityRole> roleManager, ILogger<RoleController> logger)
        {
            _roleManager = roleManager;
            _logger      = logger;
        }
        public async Task<IActionResult> Index()
        {
            var roles = await _roleManager.Roles.ToListAsync();
            return View(roles);
        }

        //ADD ROLE
        [HttpPost]
        public async Task<IActionResult> AddRole(string roleName)
        {
            if (roleName != null)
            {
                await _roleManager.CreateAsync(new IdentityRole(roleName.Trim()));
            }
            return RedirectToAction("Index");
        }

        //DELETE ROLE
        [HttpPost]
        public async Task<IActionResult> DeleteRole(string roleId)
        {
            var record = await _roleManager.FindByIdAsync(roleId);
            if (roleId != null)
            {
                await _roleManager.DeleteAsync(record);
            }
            return RedirectToAction("Index");
        }

        //UPDATE ROLE
        [HttpPost]
        public async Task<IActionResult> UpdateRole(string roleId, string roleName)
        {
            var record = await _roleManager.FindByIdAsync(roleId);
            if (roleId != null)
            {
                record.Name = roleName;
                await _roleManager.UpdateAsync(record);
            }
            return RedirectToAction("Index");
        }
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Altex/Controllers/ScanerController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Net.NetworkInformation;
using System.Runtime.InteropServices;
using System.Net;
using System.Diagnostics;
using System.IO;
using Humanizer;
using static Microsoft.AspNetCore.Razor.Language.TagHelperMetadata;
using System.Text;
using System.Configuration;
using System.Drawing;
using Altex.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using System.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Diagnostics;
using System.Net.Http;
using Microsoft.EntityFrameworkCore.Metadata.Conventions;
using Altex.Util;
using Altex.Utils;

namespace Altex.Controllers
{
    [Authorize(Roles = "Admin" )]
    public class ScanerController : ControllerExpand
    {

        //[DllImport("Iphlpapi.dll")]
        //private static extern int SendARP(Int32 dest, Int32 host, ref Int64 mac, ref Int32 length);

        //[DllImport("Ws2_32.dll")]
        //private static extern Int32 inet_addr(string ip);


        private readonly ILogger<Controller>          _logger;
        //private readonly HttpContext                  _context;
        private readonly IHttpContextAccessor         _httpContext;
        private readonly UserManager<IdentityUser>     _userManager;

        private static string  _nmap_programm_path      = "";
        private static string  _nmap_result_folder      = "";
        private static string  _nmap_result_file_XML    = "";
        private static string  _contentRootPath         = "";
        private static string  _nmap_result_folder_path = "";
        
        public ScanerController( ILogger<Controller> logger, IConfiguration configuration, UserManager<IdentityUser> userManager, IHttpContextAccessor httpContext) : base(logger, httpContext)//base( logger, context )HttpContext context, 
        {
            _userManager = userManager;
            _logger      = logger;
            _httpContext = httpContext;
            //_context     = context;
            // IHttpContextAccessor _context = Startup._httpContextAccessor;

            // Устанавливаем параметры NMap из файла настроек
            _nmap_programm_path      = configuration.GetSection("NMap_Settings").GetValue<string>("programm_path");
            _nmap_result_folder      = configuration.GetSection("NMap_Settings").GetValue<string>("result_folder");
            _nmap_result_file_XML    = configuration.GetSection("NMap_Settings").GetValue<string>("result_file_XML");
            _contentRootPath         = System.IO.Path.GetDirectoryName( System.Reflection.Assembly.GetExecutingAssembly().Location );

            _nmap_result_folder_path = Path.Combine( _contentRootPath, _nmap_result_file_XML );
        }

        // GET: ScanerController      
        public ActionResult Index()
        {

            return View();
        }

        public async Task<ActionResult> aj_scanning()
        {
            // Перехват потока вывода результатов сканирования nmap.exe
            // Не перехватывается поток в XML файл, а только стандартный поток в консоль.
            // Так как вывод результатов в XML самый полный по данным, придётся получать данные результатов сканирования через XML файл.
            // Для каждого запушеного для сканирования экземпляра nmap.exe указываем свой файл вывода XML результатов
            string log_place = "ScanerController.aj_scanning";

            #region //----------------------------------  Входные данные

            string ip_address_start = "";
            // Проверяем наличие параметра ip_start - стартовый IP-address, и его валидности значению IP-address
            if ( check_input_ip_address( ref ip_address_start, Request.Form["ip_start"], log_place + ", param:ip_start", true)) 
                return Content( convert_error_message_to_js_answer_with_errfield("Ошибка при написание значения IP-address!IDFIELD:#ip_start") );


            bool is_ip_range = false;
            // Проверяем наличие параметра is_range - значение указывает, что выбран диапазон IP адресов
            if ( check_input_bool(ref is_ip_range, Request.Form["is_ip_range"], log_place + ", param:is_ip_range", true) )
                return Content( convert_error_message_to_js_answer_with_errfield("Ошибка в значении выбора диапазона ip!IDFIELD:#is_ip_range") );

            // Конец диапазона проверяем, только если указано, что  входящие данные содержат диапазон IP адресов
            string ip_address_finish = ip_address_start;
            if ( is_ip_range )
            {
                // Проверяем наличие параметра ip_finish - конечный IP-address в диапазоне адресов, и его валидности значению IP-address
                if (check_input_ip_address(ref ip_address_finish, Request.Form["ip_finish"], log_place + ", param:ip_finish", true))
                    return Content( convert_error_message_to_js_answer_with_errfield("Ошибка при написание значения IP-address!IDFIELD:#ip_finish") );
            }

            #endregion

            // Переводим входные данные в диапазон IP
            IPAddress ip_from = IPAddress.Parse( ip_address_start  );
            IPAddress ip_to   = IPAddress.Parse( ip_address_finish );
             
            // Получаем список IP адресов диапазона
            List<IPAddress> list_ipAddres_range  = GetIPList( ip_from, ip_to);


            List<ScanResult> list_scanResults = new List<ScanResult>();

            // Производим сканирование  указанных адресов
            foreach ( IPAddress ip_address in list_ipAddres_range )
            {
                string              ip_address_text = ip_address.ToString();
                (string, ScanResult) result_scan    = await Scan_IP_async( ip_address_text );

                ScanResult scanResult = result_scan.Item2;
                // Сохраняем в список полученный результат

                list_scanResults.Add(scanResult);

                string error = await ScanUtils.save_ScanResult_async( scanResult );
            }

            ViewData["list_scanResults"] = list_scanResults;

            return PartialView("block_scan_result_table");
        }
        

        private static async Task<(string, ScanResult)> Scan_IP_async( string ip_for_scan )
        {
            string     error      = String.Empty;
            ScanResult scanResult = new ScanResult();

            try
            {
                string output_xml_file = "";
                using (var nmap_process = new Process())
                {
                    nmap_process.StartInfo.FileName        = _nmap_programm_path;
                    nmap_process.StartInfo.UseShellExecute = false;

                    string process_name = DateTime.Now.ToString("MM_dd_hh_mm_ss_") + Commons.GenerateKey_Number().ToString();
                    output_xml_file     = _nmap_result_folder_path + "/" + _nmap_result_file_XML + "_" + process_name + ".xml";
                    string arguments    = " -O " + ip_for_scan + " -oX " + output_xml_file;

                    nmap_process.StartInfo.Arguments = arguments;

                    #region // ненужный код 
                    // Временно оставил для тестов параметров перехвата потока вывода результатов от nmap.exe

                    //process.StartInfo.Arguments = string.Format("{0} {1}", Options, Target);
                    //process.StartInfo.WindowStyle = WindowStyle;
                    //process.StartInfo.RedirectStandardOutput = true;

                    //int lineCount = 0;
                    //StringBuilder output = new StringBuilder();

                    //process.OutputDataReceived += new DataReceivedEventHandler((sender, e) =>
                    //{
                    //    // Prepend line numbers to each line of the output.
                    //    if (!String.IsNullOrEmpty(e.Data))
                    //    {
                    //        lineCount++;
                    //        output.Append("\n[" + lineCount + "]: " + e.Data);
                    //    }
                    //});
                    //process.BeginOutputReadLine();

                    // Synchronously read the standard output of the spawned process.
                    //StreamReader reader = process.StandardOutput;
                    //string output_nmap = reader.ReadToEnd();
                    #endregion

                    // Стартуем  сканирование
                    nmap_process.Start();

                    // Ожидаем окончания сканирования
                    nmap_process.WaitForExit();

                    // Проверяем, создан ли XML файл результатов
                    if ( !System.IO.File.Exists(output_xml_file) )
                    {
                        // Файл не создан
                        // Это ошибка работы nmap.exe
                        // Возвращаем ошибку
                        error = "Ошибка! Не создан XML файл с результатами сканирования IP=" + ip_for_scan;
                        return (error, scanResult);
                    }

                    // Распарсиваем результаты сканирования из XML файла
                    (string, ScanResult) result_scan = await NMap_ResultXML_Parser.ParsingFileXML_async( output_xml_file, ip_for_scan );
                    error      = result_scan.Item1;
                    scanResult = result_scan.Item2;
                }
            }
            catch ( Exception ex )
            {
                error = ex.Message;
            }


            return (error, scanResult);
        }

        private List<IPAddress> GetIPList(IPAddress ipFrom, IPAddress ipTo)
        {
            List<IPAddress> ipList    = new List<IPAddress>();
            String[]        arrayFrom = ipFrom.ToString().Split(new Char[] { '.' });
            String[]        arrayTo   = ipTo.ToString().Split(new Char[] { '.' });

Altex/Controllers/UserRolesController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Altex.Data;
using Altex.Models;

namespace Altex.Controllers
{
    [Authorize(Roles = "SuperAdmin")]
    public class UserRolesController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        //private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole>    _roleManager;
        private readonly ILogger<UserRolesController> _logger;

        public UserRolesController(ILogger<UserRolesController> logger, UserManager<IdentityUser> userManager, RoleManager<IdentityRole> roleManager)
       // public UserRolesController(ILogger<UserRolesController> logger, UserManager<ApplicationUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
            _logger      = logger;
        }

        public async Task<IActionResult> Index() //It would get all the users from the database and also the roles per user.
        {
            var users              = await _userManager.Users.ToListAsync();
            var userRolesViewModel = new List<UserRolesViewModel>();
            foreach (IdentityUser user in users) //ApplicationUser
            {
                var thisViewModel       = new UserRolesViewModel();

                

                thisViewModel.UserId    = user.Id;
                thisViewModel.Email     = user.Email;

                thisViewModel.FirstName = user.UserName;
                thisViewModel.LastName  = user.PhoneNumber;

                //thisViewModel.FirstName = user.FirstName;
                //thisViewModel.LastName  = user.LastName;
                thisViewModel.Roles     = await GetUserRoles(user);
                userRolesViewModel.Add(thisViewModel);
            }
            return View(userRolesViewModel);
        }

        //private async Task<List<string>> GetUserRoles(ApplicationUser user)
        private async Task<List<string>> GetUserRoles(IdentityUser user)
        {
            return new List<string>(await _userManager.GetRolesAsync(user));
        }

        [HttpGet]
        public async Task<IActionResult> Manage(string userId)
        {
            ViewBag.userId = userId;
            var user = await _userManager.FindByIdAsync(userId);
            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with Id = {userId} cannot be found";
                return View("NotFound");
            }
            ViewBag.UserName = user.UserName;
            var model = new List<ManageUserRolesViewModel>();
            foreach (var role in _roleManager.Roles.ToList()) //This is an IQuerable the DataReaders connection will stay open until each role has been read. By using "ToList()" this problem solved.
            {
                var userRolesViewModel = new ManageUserRolesViewModel
                {
                    RoleId = role.Id,
                    RoleName = role.Name
                };
                if (await _userManager.IsInRoleAsync(user, role.Name))
                {
                    userRolesViewModel.Selected = true;
                }
                else
                {
                    userRolesViewModel.Selected = false;
                }
                model.Add(userRolesViewModel);
            }
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Manage(List<ManageUserRolesViewModel> model, string userId)
        {
            var user = await _userManager.FindByIdAsync(userId);
            if (user == null)
            {
                return View();
            }
            var roles = await _userManager.GetRolesAsync(user);
            var result = await _userManager.RemoveFromRolesAsync(user, roles);
            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Cannot remove user existing roles");
                return View(model);
            }
            result = await _userManager.AddToRolesAsync(user, model.Where(x => x.Selected).Select(y => y.RoleName));
            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Cannot add selected roles to user");
                return View(model);
            }
            return RedirectToAction("Index");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Altex/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@using Altex.Data

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Altex</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Altex.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/fonts/awesome/font-awesome.min.css" />    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Altex</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Scaner" asp-action="Index">Scan</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        @if ( SignInManager.IsSignedIn(User) )
                        {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Scaner" asp-action="List_result_scaned">List scaned IP</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Role</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="UserRoles" asp-action="Index">UserRoles</a>
                        </li>
                        }
                        

                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Altex - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/common.js" asp-append-version="true"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

    <div id="id_message" class="hd"></div>
    <div id="id_error" class="hd"></div>
    <div id="id_debug" class="hd"></div>
    <div id="do_ajax"><img src="~/img/big-roller.gif" title="Ожидание запроса" alt="Ожидание запроса" /></div>

</body>
</html>

Altex/Views/Shared/collaps_columns_panel.cshtml
@{
    Dictionary<string, Dictionary<string, string>> dct_fields_properties = (Dictionary<string, Dictionary<string, string>>)ViewData["dct_fields_properties"];
    List<string>                                   list_columns_collaps  = (List<string>)ViewData["list_columns_collaps"];
    int numb_column = 1;
}
<div id="dv_pnlclps" pnl="clps">
<div class="dv_clps_hdr">КОЛОНКИ ДЛЯ СКРЫТИЯ</div>
<table id="tb_pnlclps">
@{
    // Ключи это имена колонок которые будут выводиться
    foreach ( string name in dct_fields_properties.Keys )
    {
        if ( dct_fields_properties[name]["html"] == "skip" ) continue;
        // if (dct_fields_properties[name]["role_type_show"] == "2") continue;

        // Устанавливаем класс для визуального выделения  имён колонок которые скрыты
        string cls_td = "td_pnlclps_shw";
        if ( list_columns_collaps.Contains(name.ToLower()) ) cls_td = "td_pnlclps_hd";

        <tr>
            <td id="td_pnlclps_@name" class="@cls_td" onmouseover="_scaner.iclpspnl(this)" onmouseout="_scaner.oclpspnl(this)" onclick="_scaner.clk_clpspnl(@numb_column,'@name')">
                @name
            </td>
        </tr>

        numb_column++;
    }
}
</table>

    <input type="button" class="bt_pnl" value="Закрыть" onmouseover="_scaner.ibtn(this)" onmouseout="_scaner.obtn(this)" onclick="_scaner.pnlcls(this)" />
    <input type="button" class="bt_pnl" value="Сохранить" onmouseover="_scaner.ibtn(this)" onmouseout="_scaner.obtn(this)" onclick="_scaner.pnlclps_sv(this)" />
    <i class="fa fa-close dv_pnlcls_exit" aria-hidden="true" onmouseover="_scaner.ipnlcls(this)" onmouseout="_scaner.opnlcls(this)" onclick="_scaner.pnlcls(this)"></i>
</div>

Altex/Views/Shared/filter_by_column.cshtml
@using Altex.Util;
@using Altex.Utils;
@{
FilterByColumn filter_by_column = (FilterByColumn)ViewData["filter_by_column"];

switch( filter_by_column.type )
{
    case "datetime":
        @GeneratorHTML.filter_by_column_datetime( ref filter_by_column )
        break;
           
    case "bool":
        @GeneratorHTML.filter_by_column_bool( ref filter_by_column )
        break;
                
    default:
        @GeneratorHTML.filter_by_column( ref filter_by_column )
        break;    
} 
}